### ISSUE TITLE
ISO8601 Date Format

### ISSUE THREAD

**Issue by salorob** [JoeKuan/Highcharts_Sencha#36]
Hi JoeKuan,

I'm struggling with date fields in Sencha. 

i'm creating a rather simple chart like so:

```
this.add({
  xtype: 'highchart',
  id:'mainChart',
  series : [{
    name: valueTitle,
    type: chartType,
    step: (chartType == 'line'),
    xField : 'tsMs',
    yField : 'value'
  }],

  store: chartStore,
  chartConfig : {
....

```

based on a datastore like so:

```
{"id":2117041,"node_id":null,"item_id":60025,"favorite_id":null,"cell_id":"1","ts":"2015-11-30T17:42:52.8985290","value":0.4,"set_by":"-"},{"id":2116276,"node_id":null,"item_id":60025,"favorite_id":null,"cell_id":"1","ts":"2015-11-30T17:27:37.1539060","value":0.5,"set_by":"-"}
```

Default; Highcharts will give me 1970 dates, so something in parsing is going wrong. Alternatively i created a field that uses a Convert function to return a getTime() based on that date, like so:

```
     {
        name: 'ts',
        type: 'date'
      },
      {
        name: 'value'
      },
      {
        convert: function(v, rec) {
            return rec.get('ts').getTime();
        },
        name: 'tsMs'
      }
```

However: there i have issues with UTC again. (Chart gives record TS field an hour later, while json store shows that record with good time. 

I'd rather don't want to use the getTime() in the datamodel, as i think this is the source of this evil.

How should my date format be in the model, to be able to let this work?

**Comment by JoeKuan** [comment]
Sorry for the late reply. I am currently away for holidays for 2 weeks. I will look into the issue in next week or so.

**Comment by salorob** [comment]
Ok, looking forward to it!:)

Met vriendelijke groet,

[cid:6A47CE04-E46E-4949-891C-AE5C9CB31845]

Robert Salomons
r.salomons@ropesolutions.nlmailto:r.salomons@ropesolutions.nl
038-7779830 / 06-29359927

Van: Joe Kuan <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: JoeKuan/Highcharts_Sencha <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: vrijdag 4 december 2015 07:09
Aan: JoeKuan/Highcharts_Sencha <Highcharts_Sencha@noreply.github.com<mailto:Highcharts_Sencha@noreply.github.com>>
CC: Robert Salomons <r.salomons@ropesolutions.nl<mailto:r.salomons@ropesolutions.nl>>
Onderwerp: Re: [Highcharts_Sencha] ISO8601 Date Format (#36)

Sorry for the late reply. I am currently away for holidays for 2 weeks. I will look into the issue in next week or so.

**Comment by salorob** [comment]
Hi Joe,

Any news on this ?

Also; do you have a tip about how I can get multiple lines in one chart, in the way my data store is setup?

Met vriendelijke groet,

[cid:22D7FFC3-76B9-477D-8649-9EF59BBED7F5]

Robert Salomons
r.salomons@ropesolutions.nlmailto:r.salomons@ropesolutions.nl
038-7779830 / 06-29359927

Van: Joe Kuan <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: JoeKuan/Highcharts_Sencha <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: vrijdag 4 december 2015 07:09
Aan: JoeKuan/Highcharts_Sencha <Highcharts_Sencha@noreply.github.com<mailto:Highcharts_Sencha@noreply.github.com>>
CC: Robert Salomons <r.salomons@ropesolutions.nl<mailto:r.salomons@ropesolutions.nl>>
Onderwerp: Re: [Highcharts_Sencha] ISO8601 Date Format (#36)

Sorry for the late reply. I am currently away for holidays for 2 weeks. I will look into the issue in next week or so.

**Comment by JoeKuan** [comment]
I don't think you can convert ISO8601 Date Format with
rec.get('ts').getTime();

You need to use Ext.Date utility class to convert ISO8601 format like following:
var tmStr = rec.get('ts');
var dt = Ext.Date.parse(tmStr, 'c');

dt becomes a proper Date object, you can manipulate it to output any format, e.g. UTC time in numerical value:
return parseInt(Ext.Date.format(dt, 'U'), 10);

Ideally, you should use UTC time between graph and store. If there is discrepancy shown in the graph, then it is likely you have different timezone between your web browser and the DB storing the data.

**Comment by salorob** [comment]
Hi Joe,

I’m going crazy.

"ts":"2015-12-14T16:50:40.8399580”

If this is my date in Json data, how should my field setup in Sencha (touch) be ?

What should my setup be in Highcharts ?

I tried parsing like you suggested, but dt will always turn out to be undefined. Im going nuts..

var tmStr = rec.get('ts');
var dt = Ext.Date.parse(tmStr, 'c');

return parseInt(Ext.Date.format(dt, 'U'), 10);

Met vriendelijke groet,

[cid:041AA6B9-C3FC-4FB1-9003-01FF3597BFBE]

Robert Salomons
r.salomons@ropesolutions.nlmailto:r.salomons@ropesolutions.nl
038-7779830 / 06-29359927

Van: Joe Kuan <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: JoeKuan/Highcharts_Sencha <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: donderdag 10 december 2015 02:11
Aan: JoeKuan/Highcharts_Sencha <Highcharts_Sencha@noreply.github.com<mailto:Highcharts_Sencha@noreply.github.com>>
CC: Robert Salomons <r.salomons@ropesolutions.nl<mailto:r.salomons@ropesolutions.nl>>
Onderwerp: Re: [Highcharts_Sencha] ISO8601 Date Format (#36)

I don't think you can convert ISO8601 Date Format with
rec.get('ts').getTime();

You need to use Ext.Date utility class to convert ISO8601 format like following:
var tmStr = rec.get('ts');
var dt = Ext.Date.parse(tmStr, 'c');

dt becomes a proper Date object, you can manipulate it to output any format, e.g. UTC time in numerical value:
return parseInt(Ext.Date.format(dt, 'U'), 10);

Ideally, you should use UTC time between graph and store. If there is discrepancy shown in the graph, then it is likely you have different timezone between your web browser and the DB storing the data.

**Comment by JoeKuan** [comment]
According to the ExtJs documentation, 'convert' option is to process an existing model field to another form of value, whereas 'calculate' is to CREATE a model field out of existing model data. I think you mix up the usages of both 'convert' and 'calculate'. Since tsMs is not part of the returning data from the web server, you should use calculate.

i.e. 
     {
        calculate: function(data) {
            var tmStr = data.get('ts').getTime();
            // Make sure you do get the value
            console.log(tmStr);
            var dt = Ext.Date.parse(tmStr, 'c');
            return parseInt(Ext.Date.format(dt, 'U'), 10) \* 1000;
        },
        name: 'tsMs'
      }

**Comment by JoeKuan** [comment]
Please let me know whether you are able to interpret the date time data. So that I can close this issue.

**Comment by salorob** [comment]
Im so sorry. Yes; it looks like it works, I had to make another change though to support the iso8601 standard in my case from ServiceStack:

```
    convert: function(v, rec) {
      var dt = Ext.Date.parse(v, 'Y-m-dTH:i:s.u');
      return parseInt(Ext.Date.format(dt, 'U'), 10) * 1000;
    },
```

Van: Joe Kuan <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: JoeKuan/Highcharts_Sencha <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: dinsdag 22 december 2015 21:44
Aan: JoeKuan/Highcharts_Sencha <Highcharts_Sencha@noreply.github.com<mailto:Highcharts_Sencha@noreply.github.com>>
CC: Robert Salomons <r.salomons@ropesolutions.nl<mailto:r.salomons@ropesolutions.nl>>
Onderwerp: Re: [Highcharts_Sencha] ISO8601 Date Format (#36)

Please let me know whether you are able to interpret the date time data. So that I can close this issue.

**Comment by JoeKuan** [comment]
This is a usage issue rather than software issue. It's closed and no fix needed.
